spring:
  application:
    name: security-example
server:
  port: 8080
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration: 3600000
management:
  endpoints:
    web:
      base-path: '/actuator'
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
